In [1]:
import pandas as pd

In [2]:
names = ['K', 'J', 'I', 'D', 'E']
ages = [25, 30, 35, 28, 22]
salaries = [50000, 60000, 75000, 55000, 45000]
departments = ['IT', 'HR', 'IT', 'Finance', 'IT']

In [3]:
df = pd.DataFrame({"name": names, "age":ages, "salary": salaries, "department": departments})

In [4]:
df.head(5)

  name  age  salary department
0    K   25   50000         IT
1    J   30   60000         HR
2    I   35   75000         IT
3    D   28   55000    Finance
4    E   22   45000         IT

In [31]:
#Prepare the filter
age_filter = df['age'] > 25

#Use filter to create a dataframe
filter_df = df[age_filter]
filter_df.head(5)

  name  age  salary department
1    J   30   60000         HR
2    I   35   75000         IT
3    D   28   55000    Finance

In [32]:
age_filter

0    False
1     True
2     True
3     True
4    False
Name: age, dtype: bool

In [6]:
#Prepare the filter
department_filter = df['department'] == 'IT'

#Use filter to create a dataframe
filter_df = df[department_filter]
filter_df.head(5)

  name  age  salary department
0    K   25   50000         IT
2    I   35   75000         IT
4    E   22   45000         IT

In [8]:
#Prepare the filter
department_filter = df['department'].isin(['IT', 'HR'])
#Use filter to create a dataframe
filter_df = df[department_filter]
filter_df.head(5)

  name  age  salary department
0    K   25   50000         IT
1    J   30   60000         HR
2    I   35   75000         IT
4    E   22   45000         IT

In [19]:
filter_new = (df['age'] > 25) & ((df['salary'] > 60000))

In [20]:
filter_new

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [21]:
df[filter_new]

  name  age  salary department
2    I   35   75000         IT

In [29]:
filter_two = (df['age'] > 25)  & (df['salary'] > 60000)
filter_df = df[filter_two]
filter_df.head(5)

  name  age  salary department
2    I   35   75000         IT

In [36]:
filter_df = df.query('age > 25 and salary > 60000')
filter_df.head(5)

  name  age  salary department
2    I   35   75000         IT

In [37]:
filter_df = df.query("department == 'IT' or department == 'HR'")
filter_df.head(5)

  name  age  salary department
0    K   25   50000         IT
1    J   30   60000         HR
2    I   35   75000         IT
4    E   22   45000         IT

In [38]:
text = """This is also string"""

In [39]:
text = """This is to
demonstrate
multiline text
"""

In [40]:
text

'This is to\ndemonstrate\nmultiline text\n'

In [43]:
df.shape # (rows, columns)

(5, 4)

In [46]:
# Create new column based on existing column
df['base_salary'] = df['salary'] *0.50

In [45]:
df.head()

  name  age  salary department  base_salary
0    K   25   50000         IT      25000.0
1    J   30   60000         HR      30000.0
2    I   35   75000         IT      37500.0
3    D   28   55000    Finance      27500.0
4    E   22   45000         IT      22500.0

In [47]:
df_dropped = df.drop('base_salary', axis=1)

In [48]:
df_dropped

  name  age  salary department
0    K   25   50000         IT
1    J   30   60000         HR
2    I   35   75000         IT
3    D   28   55000    Finance
4    E   22   45000         IT

In [50]:
df_dropped = df.drop(0, axis=0)
df_dropped

  name  age  salary department  base_salary
1    J   30   60000         HR      30000.0
2    I   35   75000         IT      37500.0
3    D   28   55000    Finance      27500.0
4    E   22   45000         IT      22500.0

In [52]:
df_renamed = df.rename(columns={'base_salary': 'base_component'})
df_renamed.head()

  name  age  salary department  base_component
0    K   25   50000         IT         25000.0
1    J   30   60000         HR         30000.0
2    I   35   75000         IT         37500.0
3    D   28   55000    Finance         27500.0
4    E   22   45000         IT         22500.0

In [54]:
df['name_upper'] = df['name'].str.upper()
df.head()

  name  age  salary department  base_salary name_upper
0    K   25   50000         IT      25000.0          K
1    J   30   60000         HR      30000.0          J
2    I   35   75000         IT      37500.0          I
3    D   28   55000    Finance      27500.0          D
4    E   22   45000         IT      22500.0          E

In [55]:
# Apply uses function for creating a column
df['age_group'] = df['age'].apply(lambda x: 'young' if x <30 else 'senior')

In [56]:
df.head()

  name  age  salary department  base_salary name_upper age_group
0    K   25   50000         IT      25000.0          K     young
1    J   30   60000         HR      30000.0          J    senior
2    I   35   75000         IT      37500.0          I    senior
3    D   28   55000    Finance      27500.0          D     young
4    E   22   45000         IT      22500.0          E     young

In [58]:
def age_filter(num):
  if num < 30:
    return 'young'
  return 'senior'
df['age_group_new'] = df['age'].apply(age_filter)
df.head()

  name  age  salary department  base_salary name_upper age_group age_group_new
0    K   25   50000         IT      25000.0          K     young         young
1    J   30   60000         HR      30000.0          J    senior        senior
2    I   35   75000         IT      37500.0          I    senior        senior
3    D   28   55000    Finance      27500.0          D     young         young
4    E   22   45000         IT      22500.0          E     young         young

In [61]:
def required_filter(row):
  age = row['age']
  department = row['department']
  if age <= 30 and department == 'IT':
    return 'IT Junior'
  return 'senior'

df['staff_seg'] = df.apply(required_filter, axis=1)
df.head()

,name,age,salary,department,base_salary,name_upper,age_group,age_group_new,staff_seg
0,K,25,50000,IT,25000.0,K,young,young,IT Junior
1,J,30,60000,HR,30000.0,J,senior,senior,senior
2,I,35,75000,IT,37500.0,I,senior,senior,senior
3,D,28,55000,Finance,27500.0,D,young,young,senior
4,E,22,45000,IT,22500.0,E,young,young,IT Junior